# Generated by Django 5.2.4 on 2025-07-05 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_roomchat_usuario_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomchat',
            name='usuario_creator',
        ),
        migrations.RemoveField(
            model_name='roomchat',
            name='usuario_receiver',
        ),
        migrations.RemoveField(
            model_name='roomchat',
            name='usuario_sender',
        ),
        migrations.DeleteModel(
            name='ChatMessanges',
        ),
        migrations.DeleteModel(
            name='RoomChat',
        ),
    ]
